apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-svc
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: localhost
      http:
        paths:
          - path: /api/users/{?(.*)}
            pathType: Prefix            
            backend:
              service:
                name: auth-svc
                port: 
                  number: 3000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: client-svc
                port:
                  number: 3000
  tls:
    - secretName: ticketing-cert